### ISSUE TITLE
IddCxAdapterInitAsync failed

### ISSUE THREAD

**Issue by dailongjian** [kfroe/IndirectDisplay#2]
Hi Kfroe
I have tested the sample code you provide in Intel platform, the function IddCxAdapterInitAsync returned failed, error code was 0xC00000BB, that means it's not surported.
How can I do with this issue?
Thanks very much

**Comment by TixoRebel** [comment]
I'm having this same issue, did you ever find a solution?

**Comment by dailongjian** [comment]
The driver should not be used as a virtual driver, it should be installed on a usb device.

**Comment by TixoRebel** [comment]
Is there any way this can be a virtual driver? My goal is to create a virtual monitor so it's kinda a problem if you can't.

**Comment by dailongjian** [comment]
I have no idea on IDDM, but I develepmented a wddm filter driver on windows7,  It can be used as a virtual driver.

**Comment by TixoRebel** [comment]
Ah, thank you very much, that was my initial idea but I'm relatively new to driver development and didn't even know if a filter driver would work. Is the code public?

**Comment by dailongjian** [comment]
https://github.com/VirtualMonitor/VirtualMonitor.git
This project was developed as a prototype to be extended by its users, to make it work fine, you have a lot of hard work to to.

**Comment by TixoRebel** [comment]
Well, time to get to work then!

**Comment by dailongjian** [comment]
https://github.com/VirtualMonitor/VirtualMonitor/tree/wddm/src/VirtualMonitor_WDDM

**Comment by mgaffigan** [comment]
@dailongjian, is the problem just enumeration?  The IDDM API doesn't seem to mandate any particular USB protocol.

**Comment by dailongjian** [comment]
The phenomenon is that it doesn't work when I install it on other devices，I don't know the deeper reasons. Maybe it can be installed on USB, but I don't know how to do.

**Comment by mgaffigan** [comment]
Sorry @dailongjian, that was intended to be a question for @kfroe.  I read the thread wrong.

**Comment by douglascgh** [comment]
@mgaffigan I figure out a way to install on a  virtual device.

I was working with a unsigned build so I first had to setup kernel debugging to driver is installed correctly.
1) Enable debugger 
     bcdedit debug on
 2) Setup your debugger connection
     bcdedit /dbgsetting ...
 3) Enable testsigning or IddCxAdapterInitAsync would return 0xC00000BB
     bcdedit /set testsigning on
 4) Build driver and install with devcon
      devcon iddsampledriver.inf root\iddsampledriver

**Comment by dailongjian** [comment]
@douglascgh Perfect, thank you so much!

**Comment by dailongjian** [comment]
I tried bcdedit /set testsigning on,  It works very well.
I signed the driver, then bcdedit /set testsigning off,  but it still didn't work.
Are there any other ways ? I don't want it to work in the test mode.

**Comment by dailongjian** [comment]
Maybe signing the driver is not enough, but also requires Microsoft certification.
https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/

**Comment by jammgit** [comment]
What I done is installing on a usb device in version 1607 and installing as a virtual device in version 1703/1709. All of this work correctly before , but today, it returns 0xC00000BB in all win10 version . It is very strange. It seems I mush create a virtual usb device before install Indirect Display Driver.
